# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0003_auto_20171122_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_favorites', to='login_app.User'),
        ),
    ]
