# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20171024_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 27, 17, 42, 11, 886999), verbose_name='YYYY-MM-DD'),
        ),
    ]
