# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0016_auto_20171029_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 29, 18, 45, 21, 342025), verbose_name='YYYY-MM-DD'),
        ),
    ]
