# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0020_auto_20171029_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 3, 14, 33, 2, 653538), verbose_name='YYYY-MM-DD'),
        ),
    ]
