# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0021_auto_20171103_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 21, 23, 39, 59, 874695), verbose_name='YYYY-MM-DD'),
        ),
    ]
