# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0022_auto_20171121_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 22, 0, 5, 39, 735090), verbose_name='YYYY-MM-DD'),
        ),
    ]
