# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0040_auto_20171202_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 22, 15, 33, 24, 787706), verbose_name='YYYY-MM-DD'),
        ),
    ]
